# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

timezone: Europe/Moscow
encoding: utf-8

# Site settings
title: Few notes
description: >
  Reina de mi vida
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://patgod85.github.io" # the base hostname & protocol for your site
github_username:  patgod85

# Build settings
markdown: kramdown
