# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

timezone: Europe/Moscow
encoding: utf-8

# Site settings
title: A few notes
description: >
  gg<br/>
  V<br/>
  G<br/>
  d<br/>
  :wq<br/>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://patgod85.github.io" # the base hostname & protocol for your site
github_username:  patgod85
permalink: pretty

exclude: [README.MD, Gemfile, Gemfile.lock]
include: [git-publish-io.bat]

# Build settings
markdown: kramdown

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

gems:
  - jekyll-sitemap